using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace AnalisadorLexico.Model
{
    class Regex
    {
        List<String> keyWords;
        public Regex()
        {
            keyWords = new List<String>()
            {
                "unit",
                "interface",
                "implementation",
                "public",
                "private",
                "protected",
                "function",
                "begin",
                "end",
                "and",
                "array",
                "case",
                "const",
                "div",
                "do",
                "downto",
                "else",
                "file",
                "for",
                "function",
                "goto",
                "if",
                "in",
                "label",
                "mod",
                "nil",
                "not",
                "of",
                "or",
                "packed",
                "procedure",
                "program",
                "record",
                "repeat",
                "set",
                "then",
                "to",
                "type",
                "until",
                "var",
                "while",
                "with",
                "absolute",
                "abstract",
                "assembler",
                "automated",
                "break",
                "cdecl",
                "continue",
                "default",
                "deprecated",
                "dispose",
                "exit",
                "export",
                "external",
                "far",
                "finalization",
                "finalized",
                "forward",
                "inline",
                "interface",
                "interrupt",
                "library",
                "message",
                "near",
                "new",
                "nodefault",
                "overload",
                "override",
                "pascal",
                "platform",
                "published",
                "read",
                "readonly",
                "register",
                "reintroduce",
                "requires",
                "resident",
                "safecall",
                "sealed",
                "stdcall",
                "strict",
                "then",
                "threadvar",
                "try",
                "unit",
                "uses",
                "varargs",
                "virtual",
                "write",

            };
        }
    }
}
